// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKKtIDYLsYqBNe135pCRa7_ciQvoF9h2w',
    appId: '1:223530301019:web:65feaf5f2a01db104af17e',
    messagingSenderId: '223530301019',
    projectId: 'cafe-diary-fad89',
    authDomain: 'cafe-diary-fad89.firebaseapp.com',
    storageBucket: 'cafe-diary-fad89.firebasestorage.app',
    measurementId: 'G-X7NM640VPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrs9qUCThXXqjCKiIpBknt9MfmWacAtQk',
    appId: '1:223530301019:android:31e79695a7efbd354af17e',
    messagingSenderId: '223530301019',
    projectId: 'cafe-diary-fad89',
    storageBucket: 'cafe-diary-fad89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM9i_az38LdqedhamCIqpfYamSs-ji1gQ',
    appId: '1:223530301019:ios:c2a479181473f9064af17e',
    messagingSenderId: '223530301019',
    projectId: 'cafe-diary-fad89',
    storageBucket: 'cafe-diary-fad89.firebasestorage.app',
    iosBundleId: 'com.example.cafeDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM9i_az38LdqedhamCIqpfYamSs-ji1gQ',
    appId: '1:223530301019:ios:c2a479181473f9064af17e',
    messagingSenderId: '223530301019',
    projectId: 'cafe-diary-fad89',
    storageBucket: 'cafe-diary-fad89.firebasestorage.app',
    iosBundleId: 'com.example.cafeDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKKtIDYLsYqBNe135pCRa7_ciQvoF9h2w',
    appId: '1:223530301019:web:72bef1c40b53fbc44af17e',
    messagingSenderId: '223530301019',
    projectId: 'cafe-diary-fad89',
    authDomain: 'cafe-diary-fad89.firebaseapp.com',
    storageBucket: 'cafe-diary-fad89.firebasestorage.app',
    measurementId: 'G-WBGJ4Y8P9R',
  );
}
